"""
Generate realistic demo snapshots to replace lost historical data.
Creates believable developer snapshots with code context, summaries, and embeddings.
"""
import uuid
from datetime import datetime, timedelta
from typing import List, Dict, Any
import json
import random


class SnapshotFabricator:
    """Generate fake but realistic snapshots for demo/testing"""

    # Real code snippets from the project
    CODE_SAMPLES = [
        ("secondcortex-backend/main.py", "python", "FastAPI app initialization with authentication"),
        ("secondcortex-backend/services/vector_db.py", "python", "ChromaDB/PostgreSQL vector operations"),
        ("secondcortex-vscode/src/backendClient.ts", "typescript", "HTTP client for backend communication"),
        ("secondcortex-web/src/dashboard.tsx", "typescript", "React dashboard for snapshot timeline"),
        ("secondcortex-backend/agents/retriever.py", "python", "LLM routing and snapshot processing"),
    ]

    SUMMARIES = [
        "Fixed embedding generation timeout in vector_db service",
        "Added project-scoped snapshot queries for users",
        "Implemented fallback collection migration during Chroma failures",
        "Enhanced rate limiting for Azure OpenAI API calls",
        "Created PostgreSQL schema for snapshot persistence",
        "Deployed multi-level recovery mechanism for vector DB",
        "Optimized snapshot ingestion pipeline with queue storage",
        "Refactored authentication handler for JWT validation",
        "Added comprehensive logging to AsyncIO background tasks",
        "Implemented snapshot timeline endpoint with pagination",
        "Fixed race condition in concurrent snapshot writes",
        "Added vector embedding caching for performance",
        "Improved error handling in snapshot ingestion",
        "Refactored database connection pooling",
        "Added support for parallel snapshot processing",
    ]

    def generate_snapshots(
        self,
        user_id: str,
        project_id: str,
        count: int = 50,
        days_back: int = 30
    ) -> List[Dict[str, Any]]:
        """Generate N realistic snapshots spanning days_back days"""
        snapshots = []
        now = datetime.utcnow()

        for i in range(count):
            # Spread across time period without exceeding days_back
            offset_seconds = random.randint(0, max(0, days_back * 24 * 60 * 60))
            snapshot_time = now - timedelta(seconds=offset_seconds)

            file_name, language, context = random.choice(self.CODE_SAMPLES)
            summary = random.choice(self.SUMMARIES)

            snapshot = {
                "id": str(uuid.uuid4()),
                "project_id": project_id,
                "user_id": user_id,
                "active_file": file_name,
                "language_id": language,
                "git_branch": "main",
                "timestamp": snapshot_time.isoformat(),
                "shadow_graph": self._generate_code_context(file_name, language),
                "summary": summary,
                "entities": json.dumps(
                    ["bug_fix", "performance", "refactoring"]
                    if random.random() > 0.5
                    else ["feature_development"]
                ),
                "relations": json.dumps(
                    [
                        {"source": "vector_db.py", "type": "CALLS", "target": "llm_client.py"},
                        {"source": "retriever.py", "type": "USES", "target": "vector_db.py"},
                    ]
                ),
                "embedding": None,  # Will be generated by LLM service
                "metadata_for_search": json.dumps(
                    {
                        "context": context,
                        "difficulty": random.choice(["easy", "medium", "hard"]),
                        "file_type": language,
                    }
                ),
                "sync_status": "SYNCED",
                "ingestion_error": None,
                "created_at": snapshot_time.isoformat(),
                "updated_at": snapshot_time.isoformat(),
            }
            snapshots.append(snapshot)

        return snapshots

    def _generate_code_context(self, filename: str, language: str) -> str:
        """Generate realistic code snippet based on filename"""
        if "vector_db" in filename:
            return """async def upsert_snapshot(self, snapshot, user_id=None):
    \"\"\"Store snapshot in vector database with embedding.\"\"\"
    collection = self._get_collection(user_id)
    if collection is None:
        logger.warning("Collection not available")
        return
    
    embedding = snapshot.embedding or await self.generate_embedding(
        f"{snapshot.summary}\\n{snapshot.shadow_graph[:2000]}"
    )
    collection.upsert(
        ids=[str(snapshot.id)],
        embeddings=[embedding],
        metadatas=[{...snapshot metadata...}],
        documents=[snapshot.shadow_graph]
    )"""
        elif "retriever" in filename:
            return """async def process_snapshot(self, payload, user_id=None):
    \"\"\"Route snapshot (ADD/UPDATE/DELETE) and store in vector DB.\"\"\"
    metadata = await self._route_operation(payload, self._previous_snapshots.get(user_id))
    
    stored = StoredSnapshot(
        id=str(uuid.uuid4()),
        timestamp=payload.timestamp,
        shadow_graph=payload.shadow_graph,
        metadata=metadata,
    )
    await self.vector_db.upsert_snapshot(stored, user_id=user_id)
    return stored"""
        elif "backendClient" in filename:
            return """async sendSnapshot(payload: Record<string, unknown>): Promise<boolean> {
    const headers = await this.getHeaders();
    
    try {
        const resp = await fetch('/api/v1/snapshot', {
            method: 'POST',
            headers,
            body: JSON.stringify(payload),
        });
        return resp.status === 200;
    } catch (err) {
        this.output.appendLine(`[BackendClient] Send failed: ${err}`);
        return false;
    }
}"""
        else:
            return f"""// {filename}
// Implementation details here
function doSomething() {{
  // code
}}"""
